export const USER_HOME_REQUEST = "USER_HOME_REQUEST";
export const USER_HOME_SUCCESS = "USER_HOME_SUCCESS";
export const USER_HOME_FAIL = "USER_HOME_FAIL";

export const FIND_USER_REQUEST = "FIND_USER_REQUEST";
export const FIND_USER_SUCCESS = "FIND_USER_SUCCESS";
export const FIND_USER_FAIL = "FIND_USER_FAIL";

export const USER_SIGNUP_REQUEST  = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS  = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL  = "USER_SIGNUP_FAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

export const CURRENT_CHAT_REQUEST ="CURRENT_CHAT_REQUEST";
export const CURRENT_CHAT_SUCCESS ="CURRENT_CHAT_SUCCESS"
export const CURRENT_CHAT_FAIL ="CURRENT_CHAT_FAIL"